"""All shared data types for v18 single-responsibility agents."""

from ._advanced_types import (
    ActionSpec,
    # Layer 6: Automation
    AutoDescription,
    ChainResult,
    Conclusion,
    ConditionResult,
    ConfidenceResult,
    ConfigResult,
    ConsensusResult,
    DecomposedSteps,
    Evidence,
    EvidenceType,
    FixSuggestions,
    # Layer 9: Infrastructure
    HealthSnapshot,
    NameResult,
    PipelineResult,
    # Layer 7: Reasoning
    ProblemType,
    ReasoningResult,
    ReasoningStep,
    RiskResult,
    ScheduleSpec,
    SecurityResult,
    SyntaxResult,
    TriggerSpec,
    # Layer 5: Validation
    ValidationIssue,
    # Layer 8: Verdict
    Verdict,
    VerdictInput,
    VerdictOutput,
    WorkflowSpec,
)
from ._commerce_types import (
    # Layer 3: Commerce
    CatalogProduct,
    CatalogResult,
    CustomerInfo,
    OrderLineItem,
    OrderResult,
    OrderStatus,
    PaymentMethod,
    PaymentResult,
    PaymentStatus,
    PaymentTransaction,
    ProductType,
    ShippingAddress,
    TaxCategory,
)
from ._enterprise_types import (
    # Layer 3: Enterprise
    ComplianceFinding,
    ComplianceResult,
    ComplianceSeverity,
    ComplianceStandard,
    ContractClause,
    ContractResult,
    ContractStatus,
    ContractType,
    ProjectMilestone,
    ProjectResult,
    ProjectStatus,
    ProjectTask,
    TaskPriority,
)
from ._finance_types import (
    # Layer 3: Finance
    BudgetLineItem,
    BudgetResult,
    BudgetStatus,
    ExpenseCategory,
    ExpenseReceipt,
    ExpenseResult,
    ExpenseStatus,
    FilingStatus,
    TaxFiling,
    TaxLineItem,
    TaxResult,
    TaxType,
)
from ._intelligence_types import (
    # Layer 4: Intelligence
    AnomalyDetectionResult,
    AnomalySeverity,
    AnomalyType,
    ChurnFactor,
    CohortAnalysis,
    CompetitorProfile,
    CreditAssessment,
    CustomerInsightResult,
    CustomerProfile,
    CustomerSegment,
    DealStage,
    DetectedAnomaly,
    ForecastLine,
    ForecastPeriod,
    MarketAnalysisResult,
    MarketSegment,
    MarketTrend,
    PipelineDeal,
    PricingRecommendation,
    RiskAssessmentResult,
    RiskCategory,
    RiskFactor,
    RiskLevel,
    SalesForecastResult,
    SeasonalFactor,
    TimeGranularity,
    TrendDirection,
)
from ._documents_types import (
    # Layer 3: Documents
    ChartConfig,
    ChartType,
    DocumentCategory,
    DocumentFormat,
    DocumentLine,
    DocumentParty,
    DocumentResult,
    DocumentStatus,
    ExportFormat,
    MetricCard,
    ReportResult,
    ReportSection,
    TemplateResult,
    TemplateType,
    TemplateVariable,
)
from ._procurement_types import (
    # Layer 3: Procurement
    EvaluationResult,
    OrderPriority,
    POLineItem,
    POrderStatus,
    PaymentTerms,
    PurchaseOrderResult,
    SLAStatus,
    SLAMetric,
    ScoreCategory,
    VendorCategory,
    VendorContact,
    VendorContract,
    VendorResult,
    VendorStatus,
)
from ._core_types import (
    AgentMessage,
    # Base types
    AgentResult,
    AnalyticsResult,
    # Layer 3: Business
    BusinessData,
    BusinessData,
    CompressedContext,
    CriticalityResult,
    CRMResult,
    EntityResult,
    IntentResult,
    InventoryResult,
    InvoiceResult,
    # Layer 1: Understanding
    LanguageResult,
    # Layer 2: Memory & Context
    MemoryEntries,
    NotificationResult,
    PrefetchResult,
    ReportResult,
    RoutedOperation,
    ScoredEntries,
    ScoredEntry,
    TargetResult,
    TaskResult,
)
from ._transport_types import (
    # Layer 10: Transport
    TextChannelInput,
    TextChannelResult,
    VoiceChannelInput,
    VoiceChannelResult,
)

__all__ = [
    "ActionSpec",
    "AgentMessage",
    # Base types
    "AgentResult",
    "AnalyticsResult",
    # Layer 6: Automation
    "AutoDescription",
    # Layer 4: Intelligence
    "AnomalyDetectionResult",
    "AnomalySeverity",
    "AnomalyType",
    "ChurnFactor",
    "CohortAnalysis",
    "CompetitorProfile",
    "CreditAssessment",
    "CustomerInsightResult",
    "CustomerProfile",
    "CustomerSegment",
    "DealStage",
    "DetectedAnomaly",
    "ForecastLine",
    "ForecastPeriod",
    "MarketAnalysisResult",
    "MarketSegment",
    "MarketTrend",
    "PipelineDeal",
    "PricingRecommendation",
    "RiskAssessmentResult",
    "RiskCategory",
    "RiskFactor",
    "RiskLevel",
    "SalesForecastResult",
    "SeasonalFactor",
    "TimeGranularity",
    "TrendDirection",
    # Layer 3: Documents
    "ChartConfig",
    "ChartType",
    "DocumentCategory",
    "DocumentFormat",
    "DocumentLine",
    "DocumentParty",
    "DocumentResult",
    "DocumentStatus",
    "ExportFormat",
    "MetricCard",
    "ReportResult",
    "ReportSection",
    "TemplateResult",
    "TemplateType",
    "TemplateVariable",
    # Layer 3: Procurement
    "EvaluationResult",
    "OrderPriority",
    "POLineItem",
    "POrderStatus",
    "PaymentTerms",
    "PurchaseOrderResult",
    "SLAStatus",
    "SLAMetric",
    "ScoreCategory",
    "VendorCategory",
    "VendorContact",
    "VendorContract",
    "VendorResult",
    "VendorStatus",
    # Layer 3: Commerce
    # Layer 3: Enterprise
    "ComplianceFinding",
    "ComplianceResult",
    "ComplianceSeverity",
    "ComplianceStandard",
    "ContractClause",
    "ContractResult",
    "ContractStatus",
    "ContractType",
    "ProjectMilestone",
    "ProjectResult",
    "ProjectStatus",
    "ProjectTask",
    "TaskPriority",
    # Layer 3: Finance
    "BudgetLineItem",
    "BudgetResult",
    "BudgetStatus",
    "ExpenseCategory",
    "ExpenseReceipt",
    "ExpenseResult",
    "ExpenseStatus",
    "FilingStatus",
    "TaxFiling",
    "TaxLineItem",
    "TaxResult",
    "TaxType",
    # Layer 3: Commerce
    "CatalogProduct",
    "CatalogResult",
    "CustomerInfo",
    "OrderLineItem",
    "OrderResult",
    "OrderStatus",
    "PaymentMethod",
    "PaymentResult",
    "PaymentStatus",
    "PaymentTransaction",
    "ProductType",
    "ShippingAddress",
    "TaxCategory",
    # Layer 3: Business
    "BusinessData",
    "CRMResult",
    "ChainResult",
    "CompressedContext",
    "Conclusion",
    "ConditionResult",
    "ConfidenceResult",
    "ConfigResult",
    "ConsensusResult",
    "CriticalityResult",
    "DecomposedSteps",
    "EntityResult",
    "Evidence",
    "EvidenceType",
    "FixSuggestions",
    # Layer 9: Infrastructure
    "HealthSnapshot",
    "IntentResult",
    "InventoryResult",
    "InvoiceResult",
    # Layer 1: Understanding
    "LanguageResult",
    # Layer 2: Memory & Context
    "MemoryEntries",
    "NameResult",
    "NotificationResult",
    "PipelineResult",
    "PrefetchResult",
    # Layer 7: Reasoning
    "ProblemType",
    "ReasoningResult",
    "ReasoningStep",
    "ReportResult",
    "RiskResult",
    "RoutedOperation",
    "ScheduleSpec",
    "ScoredEntries",
    "ScoredEntry",
    "SecurityResult",
    "SyntaxResult",
    "TargetResult",
    "TaskResult",
    # Layer 10: Transport
    "TextChannelInput",
    "TextChannelResult",
    "TriggerSpec",
    # Layer 5: Validation
    "ValidationIssue",
    # Layer 8: Verdict
    "Verdict",
    "VerdictInput",
    "VerdictOutput",
    "VoiceChannelInput",
    "VoiceChannelResult",
    "WorkflowSpec",
]
