"""Core package exports — re-exports from sub-packages."""

# ruff: noqa: F405 — Star-import re-exports are intentional in this aggregator module
from __future__ import annotations

import logging

logger = logging.getLogger(__name__)

from ._exports_part1 import *  # noqa: F403, E402
from ._exports_part2 import *  # noqa: F403, E402

__all__ = [
    # Native Extension
    "HAS_NATIVE",
    "ActionOutcome",
    "AnalyticsSnapshot",
    # Phase 6: Defense
    "AntiTamperingLayer",
    # Phase 6: Approval
    "ApprovalChain",
    "ApprovalPriority",
    "ApprovalRequest",
    "ApprovalResult",
    "ApprovalStatus",
    "AuditEvent",
    "AuditEventType",
    "AuditLogger",
    "AuditSeverity",
    "AutonomyConfig",
    "AutonomyLevel",
    "AutopilotEngine",
    "AutopilotPlanner",
    "AutopilotStatus",
    "BatchRetryResult",
    "BinaryHardeningLayer",
    "BlastRadiusReport",
    "BranchCondition",
    "BranchRule",
    "ChainExecutionResult",
    "ChainStep",
    "ChainStepResult",
    "ChainTemplate",
    "ChainTemplateLibrary",
    "ChainValidationResult",
    "ChainVerificationResult",
    "ChaosExperiment",
    "ChaosExperimentRunner",
    # Phase F4: Chaos Engineering
    "ChaosExperimentState",
    "ClosedLoopFeedback",
    "ComposedChain",
    "CompositeRiskReport",
    "ConditionalBranching",
    "ContextManager",
    "ContextWindow",
    # Phase D: ROI
    "CostAccumulator",
    "CostCategory",
    "CostEntry",
    "CriticalPathReport",
    "CrossAgentKnowledgeBus",
    "DashboardWidget",
    "DeadLetterEvent",
    "DeadLetterStatus",
    "DefenseManager",
    # Phase 6: Degraded Mode
    "DegradedModeManager",
    # Phase B: Workflows
    "DynamicChainComposer",
    "EncryptionLevel",
    "EncryptionManager",
    "EventConditionOperator",
    "EventSchema",
    # WebhookIngestionEngine removed — external API connection deleted
    "EventSchemaRegistry",
    "EventValidationResult",
    "EvidenceBundle",
    "ExceptionAnalytics",
    # Phase C: Exceptions
    "ExceptionCategory",
    "ExceptionContext",
    "ExceptionEngine",
    "ExceptionPattern",
    "ExceptionRecord",
    "ExceptionRouter",
    "ExceptionSeverity",
    "ExceptionSignal",
    "FaultInjection",
    "FaultType",
    "FeedbackAction",
    "FeedbackCycle",
    "FieldMapping",
    # Phase A: Observability
    "ForensicEngine",
    "ForensicEntry",
    "ForensicReport",
    "GraphDomain",
    "HandoffResult",
    "HandoffRule",
    "HardeningLevel",
    "HardwareBindingStrength",
    "HealthAggregator",
    "HealthCheckResult",
    "HealthStatus",
    "HookRegistration",
    "HookType",
    "ImpactScore",
    "ImpactScorer",
    "IntegrityStatus",
    "IntegrityVerifier",
    "InterWorkflowHandoff",
    "IssueType",
    "KPIMeasurement",
    "KPITracker",
    "KPITrend",
    "KillSwitchStatus",
    "KnowledgeEdge",
    "KnowledgeGraphEngine",
    # Phase E1: Knowledge Graph
    "KnowledgeNode",
    "KnowledgeQuery",
    "KnowledgeSearchResult",
    "LearningEngine",
    "LearningInsight",
    "LearningStrategy",
    "LicenseInfo",
    # Phase 6: License
    "LicenseManager",
    "LicenseStatus",
    "LicenseTier",
    "LicenseVerificationResult",
    "MemoryEngineV2",
    "MemoryQuery",
    "MemoryRecord",
    "MemorySearchResult",
    # Phase E2: Memory v2
    "MemoryTier",
    "MemoryType",
    "MetricsCollector",
    "MetricsConfig",
    "ModeCapabilities",
    "ModeTransition",
    # Phase D: Autopilot
    "Objective",
    "ObjectivePriority",
    "ObjectiveStatus",
    "ObjectiveTarget",
    # Phase E3: Self-Learning
    "OutcomeStatus",
    "OutcomeTracker",
    "PlanStep",
    "PlannedAction",
    "PluginCapability",
    "PluginHookSystem",
    "PluginInstance",
    "PluginLifecycleManager",
    "PluginManifest",
    "PluginRegistry",
    # Phase F1: Plugin SDK
    "PluginState",
    "PolicyCodeEngine",
    "PolicyCondition",
    "PolicyDocument",
    # Phase F2: Policy-as-Code
    "PolicyEffect",
    "PolicyEvaluationResult",
    "PolicyOperator",
    "PolicyStatement",
    "ROIDashboardData",
    "ReplayQueue",
    "RetryResult",
    # Phase F3: Risk Prediction
    "RiskLevel",
    "RiskPredictionEngine",
    "RiskPropagationReport",
    "RoutingAction",
    "RoutingRule",
    "SecretType",
    "ServerSecretsLayer",
    "SnapshotAuditEngine",
    "SnapshotDiff",
    "SnapshotEntry",
    "SnapshotPair",
    "SteadyStateVerifier",
    "SystemMode",
    "TamperSeverity",
    "TemplateCategory",
    "TemplateStep",
    "TemplateVariable",
    "TracingConfig",
    "TrendPoint",
    "TriggerCondition",
    # Phase B: Events
    "TriggerMap",
    "TriggerMapping",
    "ValidationIssue",
    "ValueCategory",
    "ValueEntry",
    "ValueTracker",
    "WorkflowDefinition",
    "WorkflowEngine",
    "WorkflowStep",
    "ZenicException",
    "get_approval_chain",
    "get_audit_logger",
    "get_autonomy_config",
    "get_autopilot_engine",
    "get_autopilot_planner",
    "get_builtin_policies",
    "get_chain_composer",
    "get_chaos_runner",
    "get_closed_loop_feedback",
    "get_conditional_branching",
    "get_context_manager",
    "get_cost_accumulator",
    "get_cross_agent_bus",
    "get_defense_manager",
    "get_degraded_mode_manager",
    "get_exception_analytics",
    "get_exception_engine",
    "get_exception_router",
    "get_forensic_engine",
    "get_health_aggregator",
    "get_impact_scorer",
    "get_inter_workflow_handoff",
    "get_knowledge_graph",
    "get_kpi_tracker",
    "get_learning_engine",
    "get_license_manager",
    "get_memory_engine_v2",
    "get_metrics_collector",
    "get_objective_store",
    "get_outcome_tracker",
    "get_phase6_status",
    "get_plugin_hook_system",
    "get_plugin_lifecycle",
    "get_plugin_registry",
    "get_policy_code_engine",
    "get_replay_queue",
    "get_risk_prediction_engine",
    "get_roi_dashboard_data",
    "get_schema_registry",
    "get_snapshot_audit_engine",
    "get_steady_state_verifier",
    "get_template_library",
    "get_tracer",
    "get_trigger_map",
    "get_value_tracker",
    "get_workflow_engine",
    "init_tracing",
    # Phase 6: Integration
    "initialize_phase6",
    "install_builtin_policies",
    "reset_chaos_runner",
    "reset_context_manager",
    "reset_cross_agent_bus",
    "reset_knowledge_graph",
    "reset_learning_engine",
    "reset_memory_engine_v2",
    "reset_outcome_tracker",
    "reset_plugin_hook_system",
    "reset_plugin_lifecycle",
    "reset_plugin_registry",
    "reset_policy_code_engine",
    "reset_risk_prediction_engine",
    "reset_steady_state_verifier",
    "trace_span",
]
